fiber_server:
  HttpPort: ":8080"
  Mode: "Development"
  BodyLimitInKb: 102400

grpc_connection:
  EmployeeService: "127.0.0.1:50051"

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: true
  Encoding: "json"
  Level: "info"
  SugarType: true

postgres:
  ConnectionString: "host=127.0.0.1 user=kaido1712 password=kaido1712 dbname=asset_management port=5433 sslmode=disable TimeZone=Asia/Ho_Chi_Minh"

rabbitmq:
  URI: "amqps://asset_server:kaido1712@127.0.0.1:5672/asset_management"
  LabelTaskQueue: "label_task_queue"
  CompletedLabelTaskQueue: "completed_label_task_queue"

minio:
  Endpoint: "http://192.168.1.8:9000"
  AccessKeyID: "GmrlC2mP8bGnpvYZjnym"
  SecretAccessKey: "spYleTko6ZOm5F7AuWX0gqEEtnnzDWK38EWVmI27"
  AssetBucket: "asset-management"
  EmployeeBucket: "employee"

redis:
  Addr: "redis-12661.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com:12661"
  Username: "default"
  Password: "OOH5lf9owZA07XtHBtJsU8JL8se9yief"
  DB: 0

auth: 
  JwtAccessTokenKeyString: "do_an_tot_nghiep" 
  JwtAccessTokenExpireTimeInMinutes: 120