// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: module/auth/data/data_source/auth_service.proto

package datasource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	proto_share "user_service/common/proto_share"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequestRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestRPC) Reset() {
	*x = LoginRequestRPC{}
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestRPC) ProtoMessage() {}

func (x *LoginRequestRPC) ProtoReflect() protoreflect.Message {
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestRPC.ProtoReflect.Descriptor instead.
func (*LoginRequestRPC) Descriptor() ([]byte, []int) {
	return file_module_auth_data_data_source_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequestRPC) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestRPC) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginSuccessResponseRPC struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	EmployeeDetail *proto_share.EmployeeRPC `protobuf:"bytes,1,opt,name=employeeDetail,proto3" json:"employeeDetail,omitempty"`
	AccessToken    string                   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginSuccessResponseRPC) Reset() {
	*x = LoginSuccessResponseRPC{}
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSuccessResponseRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSuccessResponseRPC) ProtoMessage() {}

func (x *LoginSuccessResponseRPC) ProtoReflect() protoreflect.Message {
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSuccessResponseRPC.ProtoReflect.Descriptor instead.
func (*LoginSuccessResponseRPC) Descriptor() ([]byte, []int) {
	return file_module_auth_data_data_source_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginSuccessResponseRPC) GetEmployeeDetail() *proto_share.EmployeeRPC {
	if x != nil {
		return x.EmployeeDetail
	}
	return nil
}

func (x *LoginSuccessResponseRPC) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type VerifyAccessTokenRequestRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenRequestRPC) Reset() {
	*x = VerifyAccessTokenRequestRPC{}
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenRequestRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenRequestRPC) ProtoMessage() {}

func (x *VerifyAccessTokenRequestRPC) ProtoReflect() protoreflect.Message {
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenRequestRPC.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenRequestRPC) Descriptor() ([]byte, []int) {
	return file_module_auth_data_data_source_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyAccessTokenRequestRPC) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyAccessTokenResponseRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int32                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Exp           int64                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAccessTokenResponseRPC) Reset() {
	*x = VerifyAccessTokenResponseRPC{}
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAccessTokenResponseRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAccessTokenResponseRPC) ProtoMessage() {}

func (x *VerifyAccessTokenResponseRPC) ProtoReflect() protoreflect.Message {
	mi := &file_module_auth_data_data_source_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAccessTokenResponseRPC.ProtoReflect.Descriptor instead.
func (*VerifyAccessTokenResponseRPC) Descriptor() ([]byte, []int) {
	return file_module_auth_data_data_source_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyAccessTokenResponseRPC) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *VerifyAccessTokenResponseRPC) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyAccessTokenResponseRPC) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_module_auth_data_data_source_auth_service_proto protoreflect.FileDescriptor

var file_module_auth_data_data_source_auth_service_proto_rawDesc = string([]byte{
	0x0a, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x24, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a,
	0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x50, 0x43,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x7d, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x50, 0x43, 0x12, 0x40, 0x0a, 0x0e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x52, 0x50, 0x43, 0x52, 0x0e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x33, 0x0a, 0x1b, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x50, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x6d, 0x0a, 0x1c,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x50, 0x43, 0x12, 0x1f, 0x0a, 0x0b,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x32, 0xa8, 0x01, 0x0a, 0x0b,
	0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x50, 0x43, 0x1a, 0x1d, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x50, 0x43, 0x12, 0x5a, 0x0a, 0x11, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x21, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x50, 0x43, 0x1a, 0x22, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x50, 0x43, 0x42, 0x36, 0x5a, 0x34, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_module_auth_data_data_source_auth_service_proto_rawDescOnce sync.Once
	file_module_auth_data_data_source_auth_service_proto_rawDescData []byte
)

func file_module_auth_data_data_source_auth_service_proto_rawDescGZIP() []byte {
	file_module_auth_data_data_source_auth_service_proto_rawDescOnce.Do(func() {
		file_module_auth_data_data_source_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_auth_data_data_source_auth_service_proto_rawDesc), len(file_module_auth_data_data_source_auth_service_proto_rawDesc)))
	})
	return file_module_auth_data_data_source_auth_service_proto_rawDescData
}

var file_module_auth_data_data_source_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_module_auth_data_data_source_auth_service_proto_goTypes = []any{
	(*LoginRequestRPC)(nil),              // 0: auth.LoginRequestRPC
	(*LoginSuccessResponseRPC)(nil),      // 1: auth.LoginSuccessResponseRPC
	(*VerifyAccessTokenRequestRPC)(nil),  // 2: auth.VerifyAccessTokenRequestRPC
	(*VerifyAccessTokenResponseRPC)(nil), // 3: auth.VerifyAccessTokenResponseRPC
	(*proto_share.EmployeeRPC)(nil),      // 4: proto_share.EmployeeRPC
}
var file_module_auth_data_data_source_auth_service_proto_depIdxs = []int32{
	4, // 0: auth.LoginSuccessResponseRPC.employeeDetail:type_name -> proto_share.EmployeeRPC
	0, // 1: auth.AuthService.Login:input_type -> auth.LoginRequestRPC
	2, // 2: auth.AuthService.VerifyAccessToken:input_type -> auth.VerifyAccessTokenRequestRPC
	1, // 3: auth.AuthService.Login:output_type -> auth.LoginSuccessResponseRPC
	3, // 4: auth.AuthService.VerifyAccessToken:output_type -> auth.VerifyAccessTokenResponseRPC
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_module_auth_data_data_source_auth_service_proto_init() }
func file_module_auth_data_data_source_auth_service_proto_init() {
	if File_module_auth_data_data_source_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_auth_data_data_source_auth_service_proto_rawDesc), len(file_module_auth_data_data_source_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_auth_data_data_source_auth_service_proto_goTypes,
		DependencyIndexes: file_module_auth_data_data_source_auth_service_proto_depIdxs,
		MessageInfos:      file_module_auth_data_data_source_auth_service_proto_msgTypes,
	}.Build()
	File_module_auth_data_data_source_auth_service_proto = out.File
	file_module_auth_data_data_source_auth_service_proto_goTypes = nil
	file_module_auth_data_data_source_auth_service_proto_depIdxs = nil
}
