syntax = "proto3";

package auth;

option go_package = "module/auth/domain/service;service";

import "google/protobuf/timestamp.proto";

service AuthService {
  rpc Login (LoginRequestRPC) returns (LoginSuccessResponseRPC);
  rpc VerifyAccessToken (VerifyAccessTokenRequestRPC) returns (VerifyAccessTokenResponseRPC);
}

message LoginRequestRPC {
  string username = 1;
  string password = 2;
}


message LoginSuccessResponseRPC {
  EmployeeDetailRPC employeeDetail = 1;
  string accessToken = 2;
}

message EmployeeDetailRPC {
  int32 id = 1;
  string name = 2;
  string username = 3;
  string code = 4;
  string email = 5;
  string phone_number = 6;
  string avatar_path = 7;
  google.protobuf.Timestamp hire_date = 8;
  google.protobuf.Timestamp birthday = 9;
  google.protobuf.Timestamp created_at = 10;
  int32 department_id = 11;
  int32 position_id = 12;
  string department_name = 13;
  string department_code = 14;
  string position_name = 15;
  string position_code = 16;
}

message VerifyAccessTokenRequestRPC {
  string token = 1;
}

message VerifyAccessTokenResponseRPC {
  int32 employee_id = 1;
  string username = 2;
  int64 exp = 3;
}