// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: module/user/data/data_source/employee_service.proto

package datasource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	proto_share "user_service/common/proto_share"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIDRequest) Reset() {
	*x = FindByIDRequest{}
	mi := &file_module_user_data_data_source_employee_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIDRequest) ProtoMessage() {}

func (x *FindByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_user_data_data_source_employee_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIDRequest.ProtoReflect.Descriptor instead.
func (*FindByIDRequest) Descriptor() ([]byte, []int) {
	return file_module_user_data_data_source_employee_service_proto_rawDescGZIP(), []int{0}
}

func (x *FindByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindByNameOrCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByNameOrCodeRequest) Reset() {
	*x = FindByNameOrCodeRequest{}
	mi := &file_module_user_data_data_source_employee_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByNameOrCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByNameOrCodeRequest) ProtoMessage() {}

func (x *FindByNameOrCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_user_data_data_source_employee_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByNameOrCodeRequest.ProtoReflect.Descriptor instead.
func (*FindByNameOrCodeRequest) Descriptor() ([]byte, []int) {
	return file_module_user_data_data_source_employee_service_proto_rawDescGZIP(), []int{1}
}

func (x *FindByNameOrCodeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FindByNameOrCodeRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindByNameOrCodeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FindByNameOrCodeResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Employees     []*proto_share.EmployeeRPC `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByNameOrCodeResponse) Reset() {
	*x = FindByNameOrCodeResponse{}
	mi := &file_module_user_data_data_source_employee_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByNameOrCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByNameOrCodeResponse) ProtoMessage() {}

func (x *FindByNameOrCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_user_data_data_source_employee_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByNameOrCodeResponse.ProtoReflect.Descriptor instead.
func (*FindByNameOrCodeResponse) Descriptor() ([]byte, []int) {
	return file_module_user_data_data_source_employee_service_proto_rawDescGZIP(), []int{2}
}

func (x *FindByNameOrCodeResponse) GetEmployees() []*proto_share.EmployeeRPC {
	if x != nil {
		return x.Employees
	}
	return nil
}

var File_module_user_data_data_source_employee_service_proto protoreflect.FileDescriptor

var file_module_user_data_data_source_employee_service_proto_rawDesc = string([]byte{
	0x0a, 0x33, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x65,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x1a,
	0x24, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x52, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x4f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x09, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x50, 0x43, 0x52, 0x09, 0x65, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x73, 0x32, 0xad, 0x01, 0x0a, 0x0f, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x44, 0x12, 0x19, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x50, 0x43, 0x12, 0x59, 0x0a, 0x10,
	0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x21, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x3b, 0x64, 0x61, 0x74, 0x61, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_module_user_data_data_source_employee_service_proto_rawDescOnce sync.Once
	file_module_user_data_data_source_employee_service_proto_rawDescData []byte
)

func file_module_user_data_data_source_employee_service_proto_rawDescGZIP() []byte {
	file_module_user_data_data_source_employee_service_proto_rawDescOnce.Do(func() {
		file_module_user_data_data_source_employee_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_user_data_data_source_employee_service_proto_rawDesc), len(file_module_user_data_data_source_employee_service_proto_rawDesc)))
	})
	return file_module_user_data_data_source_employee_service_proto_rawDescData
}

var file_module_user_data_data_source_employee_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_module_user_data_data_source_employee_service_proto_goTypes = []any{
	(*FindByIDRequest)(nil),          // 0: employee.FindByIDRequest
	(*FindByNameOrCodeRequest)(nil),  // 1: employee.FindByNameOrCodeRequest
	(*FindByNameOrCodeResponse)(nil), // 2: employee.FindByNameOrCodeResponse
	(*proto_share.EmployeeRPC)(nil),  // 3: proto_share.EmployeeRPC
}
var file_module_user_data_data_source_employee_service_proto_depIdxs = []int32{
	3, // 0: employee.FindByNameOrCodeResponse.employees:type_name -> proto_share.EmployeeRPC
	0, // 1: employee.EmployeeService.FindByID:input_type -> employee.FindByIDRequest
	1, // 2: employee.EmployeeService.FindByNameOrCode:input_type -> employee.FindByNameOrCodeRequest
	3, // 3: employee.EmployeeService.FindByID:output_type -> proto_share.EmployeeRPC
	2, // 4: employee.EmployeeService.FindByNameOrCode:output_type -> employee.FindByNameOrCodeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_module_user_data_data_source_employee_service_proto_init() }
func file_module_user_data_data_source_employee_service_proto_init() {
	if File_module_user_data_data_source_employee_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_user_data_data_source_employee_service_proto_rawDesc), len(file_module_user_data_data_source_employee_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_user_data_data_source_employee_service_proto_goTypes,
		DependencyIndexes: file_module_user_data_data_source_employee_service_proto_depIdxs,
		MessageInfos:      file_module_user_data_data_source_employee_service_proto_msgTypes,
	}.Build()
	File_module_user_data_data_source_employee_service_proto = out.File
	file_module_user_data_data_source_employee_service_proto_goTypes = nil
	file_module_user_data_data_source_employee_service_proto_depIdxs = nil
}
